// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantBatchTaskExportChunksDao is internal type for wrapping internal DAO implements.
type internalMerchantBatchTaskExportChunksDao = *internal.MerchantBatchTaskExportChunksDao

// merchantBatchTaskExportChunksDao is the data access object for table merchant_batch_task_export_chunks.
// You can define custom methods on it to extend its functionality as you wish.
type merchantBatchTaskExportChunksDao struct {
	internalMerchantBatchTaskExportChunksDao
}

var (
	// MerchantBatchTaskExportChunks is globally public accessible object for table merchant_batch_task_export_chunks operations.
	MerchantBatchTaskExportChunks = merchantBatchTaskExportChunksDao{
		internal.NewMerchantBatchTaskExportChunksDao(),
	}
)

// Fill with you ideas below.
