// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"unibee/internal/dao/default/internal"
)

// internalMerchantCheckoutDao is internal type for wrapping internal DAO implements.
type internalMerchantCheckoutDao = *internal.MerchantCheckoutDao

// merchantCheckoutDao is the data access object for table merchant_checkout.
// You can define custom methods on it to extend its functionality as you wish.
type merchantCheckoutDao struct {
	internalMerchantCheckoutDao
}

var (
	// MerchantCheckout is globally public accessible object for table merchant_checkout operations.
	MerchantCheckout = merchantCheckoutDao{
		internal.NewMerchantCheckoutDao(),
	}
)

// Fill with you ideas below.
